domain_path: /projects/Vitis_Unified_Workspace/platform/export/platform/sw/freertos_psu_cortexa53_0
app_src_dir: /tools/Xilinx/2024.1/Vitis/2024.1/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
